"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: AtcData
  IDL file: AtcData.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.mutable
@annotate.autoid("hash")
@annotate.nested
class Position(idl.IdlStruct, typename="AtcData.Position"):
    latitude: types.float64
    longitude: types.float64


@dataclass
@annotate.mutable
@annotate.autoid("hash")
class Flight(idl.IdlStruct, typename="AtcData.Flight"):
    id: str
    annotate.key("id")
    pos: 'AtcData.Position'
    CurrentRegion: str


